### ISSUE TITLE
How to use this library in a ktor project?

### ISSUE THREAD

**Issue by hamza-maqsood** [bkbnio/kompendium#166]
I am struggling to find out on how to use it in a ktor project?

There are no instructions in the readme or anything

**Comment by unredundant** [comment]
all docs are now published here https://bkbnio.github.io/kompendium

**Comment by unredundant** [comment]
the playground module also contains a number of useful examples
https://github.com/bkbnio/kompendium/tree/main/kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground

**Comment by unredundant** [comment]
but if you have any specific questions that aren't answered in those places, I've opened a discussion for general documentation improvements here https://github.com/bkbnio/kompendium/discussions/167 

V2 was just released a couple days ago and it was a complete rehaul to the library, so if there are any issues you run into let me know!

**Comment by hamza-maqsood** [comment]
I see...
I was hoping for some kind of quick starter, it would be better if there were a quick starter in the readme or even on the [link](https://bkbnio.github.io/kompendium) with a few basic endpoints examples
and then the developer could go in depth as needed

but anyways, thanks for the quick response, I'll explore ti

**Comment by unredundant** [comment]
The playground is a collection of quick starters, very targeted at specific features.  

Any recommendations at how to make that more clear in the readme?
