### ISSUE TITLE
Swagger UI does not show the example response body

### ISSUE THREAD

**Issue by MarcelBochtler** [bkbnio/kompendium#184]
**Describe the bug**
While the ReDoc UI shows the example body implemented as a `ResponseInfo`, the Swagger UI only shows default values for the body, like `0` for Ints and `"string"` for Strings.

**To Reproduce**
1. Use `swagger()`
2. Implement a `ResponseInfo` with `examples`.

**Expected behavior**
The Swagger UI should show the actual examples instead of default values.

**Screenshots**
Example body a shown by Swagger UI:
```json
{
  "buildId": 0,
  "currentStage": "string",
  "endTime": {
    "seconds": 0,
    "nanos": 0
  },
  "startTime": {
    "seconds": 0,
    "nanos": 0
  },
  "statistics": {}
}
```

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Browser Firefox
 - Version 96.0.3

**Comment by unredundant** [comment]
Hmmm interesting 🤔 TBH I don't really use swagger very much, but I know it is a crowd favorite so I made sure to try to support it :) 

I can try to replicate this on my end, but feel free to dig around and see if u can find a fix

**Comment by unredundant** [comment]
figured out the issue... I had initially copy pasta'd over an older version of Swagger.  Bumping all the assets up to Swagger 4.5 seems to have resolved this.
