### ISSUE TITLE
Jackson serializer requires Include.NON_NULL option

### ISSUE THREAD

**Issue by MarcelBochtler** [bkbnio/kompendium#185]
**Is your feature request related to a problem? Please describe.**
Kompendium currently uses the installed serializer.
For Jackson it requires the `setSerializationInclusion(JsonInclude.Include.NON_NULL)` option to display ReDoc and Swagger UI correctly.
This option might not be wanted for the installed serializer used by Ktor.

**Describe the solution you'd like**
How about providing an option to pass a separate serializer instance.

**Describe alternatives you've considered**
An alternative would be to not require specific serializer options for Kompendium.

**Comment by unredundant** [comment]
Thanks for opening this issue! I agree this is not optimal (same issue exists for kotlinx serialization... requires a some specific configuration that I'm not a fan of) 

> How about providing an option to pass a separate serializer instance.

A problem I see there is that at the moment, Kompendium is configured to leverage whatever serializer you set for the API.  So this means that Gson, Kotlinx, and Jackson all work out of the box.  I'm not sure what an interface would look like that would support all of them as potential overrides.

**Comment by unredundant** [comment]
Above is a draft PR with a potential solution to this... hasn't been rigorously tested yet, just an anecdotal success using a playground example.

**Comment by unredundant** [comment]
Also, neat peak into the future, in Ktor 2, you will be able to install specific plugins for a given route https://ktor.io/docs/eap/plugins.html#install-route which means that in a future version, Kompendium can install a custom content negotiator directly on just its route
