### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by MarcelBochtler** [bkbnio/kompendium#186]
If my team decides to go with Kompendium for the OpenAPI generation, we would most likely also contribute.
To get the approval by our company to contribute to this repository, a documentation of the contribution process is required.

Can you consider adding this documentation as part of a `CONTRIBUTING.md` file?

**Comment by unredundant** [comment]
Sure :) 

I would need to adjust it to make sense for Kompendium, but this https://github.com/github/docs/blob/main/CONTRIBUTING.md seems like a pretty good starting point.  

Do you have any other examples of good `CONTRIBUTING.md` files?

**Comment by MarcelBochtler** [comment]
The project we're mainly working on uses [this CONTRUBUTING.md](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md).
But GitHub's own contribution guidelines seem of course like a good starting point.
