### ISSUE TITLE
SimpleSchema chema added via addCustomTypeSchema ignores format field if specified.

### ISSUE THREAD

**Issue by netknight** [bkbnio/kompendium#198]
**Describe the bug**
If I use such configuration:
```
install(Kompendium) {
    spec = Util.baseSpec
    // Tells Kompendium how to handle a specific type
    addCustomTypeSchema(Instant::class, SimpleSchema(type = "string", format = "date-time"))
  }
```

and will use `Instant` type in models - `format` setting will be ignored.

**To Reproduce**
1. Oepn `CustomTypePlaygroind` example in `kompendium-playground` module
2. Change install part as described above.
3. Lanuch `main()`
4. Open `/openapi.json` and you'll see for `Instant` field such definition:
```
"timestamp": {
   "type": "string"
}
```

**Expected behavior**
There should be such definition:
```
"timestamp": {
   "type": "string",
   "format": "date-time"
}
```

**Additional context**
Format may be important in some cases because it helps Swagger UI to identify how example must be generated according to it.

**Comment by unredundant** [comment]
Ahhh this is a design oversight on my part, but good news is that there is a working solution :) 

## Solution

What you need is `FormattedSchema`... so for example, 

```
addCustomTypeSchema(Instant::class, FormattedSchema("string", "date-time"))
```

## History lesson 😄

Initially, Kompendium didn't have a `format` field in `SimpleSchema`.  It was added after the fact to support custom constraints on simple types... so users could do something like this 

```
  @Serializable
  data class ConstrainedParams(
    @Field(description = "This is a really important field!")
    @Param(ParamType.QUERY)
    @MinLength(11)
    @MaxLength(11)
    @Pattern("^\\d{3}-\\d{2}-\\d{4}\$")
    @Format("password")
    val ssn: String = "111-11-1111"
  )
```

(See the `ConstraintPlayground` for the working example.)

One potentially way to make this less confusing would be to remove `format` from the `SimpleSchema` constructor, and only make it internally accessible.  Then, users can continue to use `@Format` to override specific instances of simple types, but won't run into the same problem as you when trying to add custom type definitions.

TBH I'm kinda surprised it doesn't work, I would have assumed that setting the `format` inside the `SimpleSchema` would propagate to the end schema, even though that wasn't the intention to begin with.

**Comment by netknight** [comment]
There is no problem in docs format, at least having KDoc description what particular class was invented for would give better understanding how should it be used. 
For example I'm trying to find a solution for multipart/form-data. I've found a way to just add a file or even 2 at once passing such object as request parameter:
```kotlin
@Serializable
        @Serializable
        data class MultipartContent(
            @Format("binary")
            val file1: String,
            @Format("binary")
            val file2: String
        )
```
And it renders correct `openapi.json` with 2 file fields:
```json
{
  "multipart/form-data": {
    "schema": {
      "properties": {
        "file1": {
          "type": "string",
          "format": "binary"
        },
        "file2": {
          "type": "string",
          "format": "binary"
        }
      },
      "required": [
        "file1",
        "file2"
      ],
      "type": "object"
    }
  }
}
```

But if I want use here file for first property and schema for second one - it won't work (file will be rendered correctly but schema will be rendered as a simple string).
Here an example what I'm trying to achieve:
```yaml
multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                request:
                  $ref: "#/components/schemas/MyRequest"
              required:
                - file
                - request
```

**Comment by netknight** [comment]
Looks like solved last one :)

**Comment by unredundant** [comment]
Not sure how you're generating the `$ref` at the moment (Adding a custom `ReferenceSchema`?) but I'm working on #181 which will move all object schemas into the component schemas, and then reference them in requests/response bodies.  Reason being is that it plays way nicer with client generators as mentioned in #176

**Comment by unredundant** [comment]
Glad you solved it though :)
