### ISSUE TITLE
Unable to use sealed typed collections

### ISSUE THREAD

**Issue by ydanneg** [bkbnio/kompendium#199]
Kompendium fails when dealing with sealed typed (polymorphic) collection in response or request.
Error:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to parse field type from val io.bkbn.kompendium.playground.FieldValue.name: kotlin.String
	at io.bkbn.kompendium.core.handler.ObjectHandler.handleDefault(ObjectHandler.kt:88)
	at io.bkbn.kompendium.core.handler.ObjectHandler.generateFieldMap(ObjectHandler.kt:70)
	at io.bkbn.kompendium.core.handler.ObjectHandler.handle(ObjectHandler.kt:50)
	at io.bkbn.kompendium.core.Kontent$generateKTypeKontent$2.invoke(Kontent.kt:94)
	at io.bkbn.kompendium.core.util.Helpers.logged(Helpers.kt:26)
	at io.bkbn.kompendium.core.Kontent.generateKTypeKontent(Kontent.kt:76)
	at io.bkbn.kompendium.core.handler.CollectionHandler.handle(CollectionHandler.kt:30)
...
```

```kotlin
@Serializable
data class Response(
  val values: List<FieldValue>
)

@Serializable
@JsonClassDiscriminator("type")
sealed class FieldValue {
  abstract val name: String
  abstract val value: String

  @Serializable
  @SerialName("text")
  data class Text(override val name: String, override val value: String) : FieldValue()

  @Serializable
  @SerialName("signature")
  data class Signature(override val name: String, override val value: String, val signed: Boolean) : FieldValue()
}
```

The crash happens here when trying to get field type of a sealed class.
https://github.com/bkbnio/kompendium/blob/c8f64a50b0094957a5fda20dcf2ccd8f3df8d035/kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/handler/ObjectHandler.kt#L88

If I remove the following line then everything works perfect (including Swagger):
https://github.com/bkbnio/kompendium/blob/c8f64a50b0094957a5fda20dcf2ccd8f3df8d035/kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/handler/CollectionHandler.kt#L30

**Comment by ydanneg** [comment]
Seems this call is not needed there at all?
I also think the same would happen with abstract classes and interfaces.

**Comment by unredundant** [comment]
Interesting.... we definitely need that line there, that ensures that the type of the collection is available in the schema cache.  You can verify by running the tests with that line commented `./gradlew test` lots of things will break.  I'm actually pretty surprised that it works at all if you comment out that line, but perhaps you declare this class somewhere else outside of a collection? then it would already exist in the cache and Kompendium would just skip it.  

My guess is this is a bug with the way Kompendium scans and analyzes sealed classes.

**Comment by ydanneg** [comment]
it probably should be moved 11 lines down:  only if not sealed.

**Comment by unredundant** [comment]
Great spot 👌 do you want to push out a PR for it, since you identified the fix? 

Doing that breaks one test, but the thing it breaks is a small bug that I identified previously and was going to try to fix this weekend anyway.

So I think you killed two birds with one stone :) Amazing!
