### ISSUE TITLE
LocationAPI params are ignored if not annotated with ParamType

### ISSUE THREAD

**Issue by netknight** [bkbnio/kompendium#218]
**Is your feature request related to a problem? Please describe.**
The current implementation require `@Param` annotations like this:
```kotlin
@Location("test/{name}")
  data class TestLocations(
    @Param(ParamType.PATH)
    val name: String,
  )
```

but there is no point in such annotations because parameter type can be calculated using Location object (the same way like `KTor` does it). 

**Describe the solution you'd like**
Annotations should be optional and by default the `KTor` way should be used.

**Comment by unredundant** [comment]
Hmmm... I guess this is feasible, but can't a location live nested within a normal route? not sure how it would work in that case.

I personally like the declarative nature of saying X is a path parameter, Y is a query parameter, Z is a header, etc. etc., but if you were to make a PR modifying the location module to allow it to support both the explicit and implicit approaches, I'd be fine merging that :)

**Comment by netknight** [comment]
I'll try to find some time for that.

**Comment by unredundant** [comment]
I'm gonna close this.  V3 handles parameters much differently than past versions, and I think the declarative approach is how Kompendium is going to keep as it's approach going forward.  Ultimately, it is not much extra lift to write out the extra parameter details.  

If you do ever want to submit a PR for v3 that implements this feature, I'm happy to look at it and merge it if it feels right :)
