### ISSUE TITLE
Example with simple documentation

### ISSUE THREAD

**Issue by yashsamit** [bkbnio/kompendium#224]
A simple example with basic config is required. Documentation is missing this important part.

Thanks for wonderful project!

**Comment by unredundant** [comment]
Hey 👋 Glad you like the project! 

Documentation is definitely an area that Kompendium could improve in.  At the moment, the best place to look for examples is in the [playground module](https://github.com/bkbnio/kompendium/tree/main/kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground).  These can all be run independently to explore a variety of use cases.  If you're looking for a simple example, I recommend the [basic playground example](https://github.com/bkbnio/kompendium/blob/main/kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/BasicPlayground.kt).  

Hope that helps!
