### ISSUE TITLE
Mismatch error

### ISSUE THREAD

**Issue by yashsamit** [bkbnio/kompendium#226]
Current code:
`companion object Feature : ApplicationFeature<Application, Configuration, Kompendium> {
    override val key: AttributeKey<Kompendium> = AttributeKey("Kompendium")
    override fun install(pipeline: Application, configure: Configuration.() -> Unit): Kompendium {
      val configuration = Configuration().apply(configure)
      val routing = pipeline.routing { }
      configuration.openApiJson(routing, configuration.spec)
      return Kompendium(configuration)
    }
  }`

New version of Ktor required something like below

`public companion object Plugin : ApplicationPlugin<ApplicationCallPipeline, Configuration, CORS> 
`

Both latest 1.x and 2.x : https://ktor.io/docs/eap/pipelines.html#ktor-pipelines

Facing Error
`Type mismatch.
Required:
Plugin<TypeVariable(P), TypeVariable(B), TypeVariable(F)>
Found:
OpenAPIGen.Feature`

**Comment by yashsamit** [comment]
https://github.com/ktorio/ktor/blob/b5b59ca3ae61601e6175f334e6a1252609638e61/ktor-server/ktor-server-plugins/ktor-server-data-conversion/jvmAndNix/src/io/ktor/server/plugins/dataconversion/DataConversion.kt

For example what is the new way.

**Comment by unredundant** [comment]
Kompendium doesn't support Ktor 2, and probably won't given that the Jetbrains team is working on their own openapi generator from my understanding.  

But, I don't think what you said is true about Ktor 1.x 

Kompendium is running its entire test suite against ktor 1.6.8 which is the latest 1.x version.  

Are you sure you are experiencing this error with Ktor 1?

**Comment by unredundant** [comment]
Gonna close this, feel free to comment if there are any outstanding questions
