### ISSUE TITLE
After upgrading org.webjars.swagger-ui to version 4.9.1 - kompendium-swagger-ui is not working anymore

### ISSUE THREAD

**Issue by netknight** [bkbnio/kompendium#236]
**Describe the bug**
In new version Swagger UI resources structure has changed:
initialization part was moved out from `index.html` to a separate file `swagger-initializer.js`

**To Reproduce**
Just launch `SwaggerPlayground.kt` and you'll see a default pet project instead of configured one.

**Expected behavior**
Correct API should be generated as defined with SwaggerUI plugin.

**Additional context**
Please check ALWAYS Swagger-UI Playground project after org.webjars.swagger-ui library updates.

I'll add a PR with fix.

**Comment by unredundant** [comment]
> Please check ALWAYS Swagger-UI Playground project after org.webjars.swagger-ui library updates.

This should be captured by a test, not by an expectation of manual work on every release.  The best way to make sure this regression won't happen again will be to add a unit tests along side your PR to ensure that all files are loaded as expected.
