### ISSUE TITLE
Support empty body PUT request

### ISSUE THREAD

**Issue by henrikix** [bkbnio/kompendium#242]
**Is your feature request related to a problem? Please describe.**
Currently `data class PutInfo<TParam, TReq, TResp>` parameter `requestInfo` is defined as non-nullable.
I would suggest changing it to an optional similarly to `PostInfo` so PUT requests could be supported with an empty request body.

I am open to creating a pull request, if this is acceptable.

**Comment by unredundant** [comment]
You can do this `PutInfo<Unit, Unit, BasicResponse>`

**Comment by henrikix** [comment]
It still requires me to build a `RequestInfo` object, how does `Unit` help me here?

**Comment by unredundant** [comment]
Oh yea.... my bad misread your original question, I thought you were just asking about how to have an empty request type.  

Yea that makes sense, it's a super easy fix, just pushed one, release should hit maven central in 10 ish minutes

**Comment by henrikix** [comment]
Thanks!
