### ISSUE TITLE
Field-Annotation description does not work

### ISSUE THREAD

**Issue by Goul85** [bkbnio/kompendium#245]
**Describe the bug**
when annotating a property with `@Field(description="some description")` the description is ignored

**Cause**
in kompendium.core.handler.ObjectHandler.kt - ComponentSchema.adjustForFieldOverrides
the line 114 - this.setDescription(fieldOverrides.description)
the returned copy of the ComponentSchema is never used and the original ComponentSchema is returned by the function

**Proposed fix**
```
  private fun ComponentSchema.adjustForFieldOverrides(prop: KProperty1<*, *>): Pair<String, ComponentSchema> {
    var name = prop.name
    var spec = this
    prop.findAnnotation<Field>()?.let { fieldOverrides ->
      if (fieldOverrides.description.isNotBlank()) {
        spec = this.setDescription(fieldOverrides.description)
      }
      if (fieldOverrides.name.isNotBlank()) {
        name = fieldOverrides.name
      }
    }
    return Pair(name, spec)
  }
```

**Comment by Goul85** [comment]
I tried the proposed fix with a local release and ran into another issue. The description for a field does not get attached to the property but rather to the object. This leads to the error "Slug cannot be null for an object schema!" in certain situations.

Referencing the same object with different descriptions breaks the generation.
```
@Serializable
data class Foo(
    @Field(description = "description1")
    val test: Bar
)

@Serializable
data class Fuu(
    @Field(description = "description2")
    val test: Bar
)

@Serializable
data class Bar(
    val test: String
)
```

**Comment by unredundant** [comment]
what version of kotlin, ktor and kompendium are you using?  I'm pretty sure we have a test in place that validates this behavior, but bugs are always possible :)

**Comment by unredundant** [comment]
Ah i see, the test case json does not have the description either.  Makes sense why that is passing then :D easy to miss this kinda stuff

**Comment by unredundant** [comment]
I believe the reason for the second bug you mention is that kompendium does an object comparison to what is in the cache, and likely the object in the cache _has_ a description, and the object it is comparing does not.  

This is a pretty bad design on my part.  However, I believe we can get around this by simply removing description from the object comparison.

With that said, this project is now _super_ low on my personal priorities list, so this fix will likely need you or someone from the community to tackle it if time is of the essence.


Also, Jetbrains is supposedly working on their own solution for openapi generation for Ktor 2 (which was released today 🎉)

**Comment by unredundant** [comment]
field annotations have been deprecated, and will be completely rehauled prior to the official kompendium v3 release.  Going to close this
