### ISSUE TITLE
Is there any way to protect openapi resource with any auth?

### ISSUE THREAD

**Issue by Kulikovpavel** [bkbnio/kompendium#277]
Case:
I need to create protected page with swagger/openapi definitions, but I want to close it from public?

How can I do that?

**Comment by unredundant** [comment]
Never tried it personally, but I don't see why something like the following wouldn't work 

```kotlin
openApiJson = {
  authenticate("basic") {
    route("/openapi.json") {
      get {
        call.respond(HttpStatusCode.OK, spec)
      }
    }
  }
}
```

**Comment by unredundant** [comment]
This will be fixed in the next release, most likely v3-beta.  However, this will only support Ktor 2, just a heads up
