### ISSUE TITLE
v3 Field level constraints

### ISSUE THREAD

**Issue by unredundant** [bkbnio/kompendium#289]

**Comment by jvgelder** [comment]
You may consider using `require` here. You do how ever need a standerdized way of building the rule to access the constrains.
Poking  @mtrojahn  to open source his require lib :)

**Comment by unredundant** [comment]
x-posting from #407 

Hmmm... a potential solution just popped into my head... there could be some sort of DSL where users could assign certain metadata to a field using kotlin field accessors. So for a class

```kotlin
data class MyData(val a: String, val b: Int)
```

a corresponding metadata definition would look something like the following

```kotlin
val metadata = KompendiumMetadata { 
  MyData::a {
    deprecated("My deprecation message")
    regex("[^a-zA-Z]")
  }
  MyData::b {
    maxValue(42)
  }
}
```

See [here](https://github.com/konform-kt/konform) for a validation library that has a similar approach.

The key benefits here are that

The primary flaw to the annotation based approach of Kompendium V2 (in my opinion) was that if you ever wanted to have different field metadata on the same data, you would need two separate data classes.
users don't need to modify their data classes directly (sticking with kompendium's non-invasive ethos), and allows users to assign different metadata to the same data class on any given route.
