### ISSUE TITLE
Add support for ktor Resources in addition to / instead of Locations

### ISSUE THREAD

**Issue by serpro69** [bkbnio/kompendium#356]
**Is your feature request related to a problem? Please describe.**

According to [Locations documentation](https://ktor.io/docs/locations.html), the plugin is deprecated and [Resources](https://ktor.io/docs/type-safe-routing.html) should be used instead:

> In v2.0.0, the Locations plugin is deprecated. Use the [Resources](https://ktor.io/docs/type-safe-routing.html) plugin instead.

**Describe the solution you'd like**

Replace the kompendium-locations plugin with kompendium-resources. Looking at the code, a simple copy-paste of existing plugin code with some renaming and adding support for `Resource` annotations should do the trick. (Can also just add a new plugin in addition to existing locations, but I don't see much point in keeping a plugin for deprecated ktor functionality.)

**Describe alternatives you've considered**

The workaround I'm using now is annotating the resource with both `Location` and `Resource` annotations. It seems to work, but is not a very good option.

**Comment by unredundant** [comment]
Makes sense 👍 

For the sake of backwards compatibility we should just make a new module for resources and port over most of the code (it's not a very big module).  

Then we'll mark locations as deprecated and remove it in the next major release.

**Comment by unredundant** [comment]
@serpro69 is this something you'd like to tackle?

**Comment by serpro69** [comment]
Sure, I can take a look at it.

**Comment by serpro69** [comment]
Made a draft PR with the new module.

The `resources` name kind of irks me, but I don't have a better one, since that's how ktor plugin is also called. Let me know what you think :)

**Comment by unredundant** [comment]
yea i had this thought as well... We could go with `resources-plugin`, but IMO neither feel great

**Comment by serpro69** [comment]
Yeah, I thought about `resource-plugin` also, but decided to keep the dir named following the same convention as existing plugins. 
Maybe prefixing all plugins directories with `kompendium-` and/or postfixing with `-plugin` would help a little?
Another suggestion would be to move all auxiliary plugins to a `plugins` dir and only prefix with `kompendium-`. 
Either of these makes things a bit cleaner and clearer, IMO.

But this should probably be discussed/done in a separate issue.

**Comment by unredundant** [comment]
yea anything like that would need to be done as part of a major version bump, since it would break backwards compatibility

**Comment by unredundant** [comment]
Kinda weird the github jobs to push to github packages and nexus are failing 🤔 https://github.com/bkbnio/kompendium/actions/runs/3351393477/jobs/5552818811 

I just tried publishing to my local maven repo and everything seems fine, so I'm gonna assume this is some github actions issue for now. I'll try republishing later today and look into it more if it still fails.

**Comment by unredundant** [comment]
ok just reran it and everything worked, so must have been some transient issue with Github actions... the changes are now released.
