### ISSUE TITLE
response type displaying empty objets

### ISSUE THREAD

**Issue by ohlmanjesse** [bkbnio/kompendium#362]
**Describe the bug**
In version 3.5.0 the response type displays empty objects for types that are not objects.

**To Reproduce**
Create a data class with nullable fields
Pass the class into the responseType in response {...}
Every field set to be nullable will display an empty object in the docs

**Expected behavior**
Even though the field is nullable, I expect it to show th type ie. String? = "string" and Int? = 0

**Screen shots**
![Screen Shot 2022-11-01 at 1 18 51 PM](https://user-images.githubusercontent.com/66743652/199319859-a2a360ed-d6a0-4811-a8c2-6e95e811c53a.png)

**Comment by unredundant** [comment]
hmm... Are you sure this was introduced in the latest release only? 

If you could inspect the actual `openapi.json` and paste the schema for this object here that would be super useful.  

I have a feeling that redoc may just not be displaying this correctly.  The way that kompendium handles nullable fields is that it declares a `oneOf` json schema, with the type and null as the two entries. 

Or, it could be a bug w/ Kompendium :) but we'll know after we see the payload.

**Comment by ohlmanjesse** [comment]
This is what I see for that section in the openapi.json
 ```{"RegistrationStateRuleResponseBody":{"type":"object","properties":{"int":{"type":"number","format":"int32"},"nullableInt":{"oneOf":[{"type":"null"},{"type":"number","format":"int32"}]},"nullableString":{"oneOf":[{"type":"null"},{"type":"string"}]},"string":{"type":"string"}},"required":["int","string"]}```

And this is what I see for version 2.3.5 (working as expected)
```"components":{"schemas":{"RegistrationStateRuleResponseBody":{"properties":{"int":{"format":"int32","type":"integer"},"nullableInt":{"format":"int32","type":"integer","nullable":true},"nullableString":{"type":"string","nullable":true},"string":{"type":"string"}},"required":["nullableInt","nullableString","int","string"],"type":"object"}```

**Comment by unredundant** [comment]
Yea so these are actually both correct as far as I can tell.  The reason for the difference is that in V3, Kompendium moved to OpenAPI spec 3.1, which is fully JsonSchema compliant, where as V2 was built to generate Openapi 3.0, which was a sort of pseudo JsonSchema.  

Just to check, I put the V3 json blob into a JsonSchema validator and it seems fine at a glance 

<img width="1753" alt="Screenshot 2022-11-01 at 6 37 45 PM" src="https://user-images.githubusercontent.com/5607577/199355190-0cd09135-7b12-47f0-b4ff-9e520664aab7.png">

This looks like a bug in ReDoc's generation to me.  Could you open an issue with them and see what they say? I'm going to close this but feel free to open it back up if necessary

## V3

```json
{
   "RegistrationStateRuleResponseBody":{
      "type":"object",
      "properties":{
         "int":{
            "type":"number",
            "format":"int32"
         },
         "nullableInt":{
            "oneOf":[
               {
                  "type":"null"
               },
               {
                  "type":"number",
                  "format":"int32"
               }
            ]
         },
         "nullableString":{
            "oneOf":[
               {
                  "type":"null"
               },
               {
                  "type":"string"
               }
            ]
         },
         "string":{
            "type":"string"
         }
      },
      "required":[
         "int",
         "string"
      ]
   }
}
```
## V2

```json
{
   "schemas":{
      "RegistrationStateRuleResponseBody":{
         "properties":{
            "int":{
               "format":"int32",
               "type":"integer"
            },
            "nullableInt":{
               "format":"int32",
               "type":"integer",
               "nullable":true
            },
            "nullableString":{
               "type":"string",
               "nullable":true
            },
            "string":{
               "type":"string"
            }
         },
         "required":[
            "nullableInt",
            "nullableString",
            "int",
            "string"
         ],
         "type":"object"
      }
   }
}
```

**Comment by unredundant** [comment]
Happy to help :) 

Just as a quick follow up I was looking more into this, and if you click on the response dropdown, redoc correctly describes nullable properties as `null or X`.  So they do correctly parse this info elsewhere, just not in the dummy response. 

<img width="1022" alt="Screenshot 2022-11-02 at 11 20 40 AM" src="https://user-images.githubusercontent.com/5607577/199529284-a232a303-561e-4bff-9f9f-36d7795ec6c8.png">
