### ISSUE TITLE
Support route where some methods are authenticated

### ISSUE THREAD

**Issue by geirsagberg** [bkbnio/kompendium#372]
**Is your feature request related to a problem? Please describe.**
I have an endpoint where the GET method is public but the PUT method needs authentication:

```kotlin
route("/item/{id}") {
  get {
    ...
  }
  authenticate {
    put {
      ...
    }
  }
}
```

- If I install the `NotarizedRoute` next to the `get` method, it will not introspect the authentication, which will be wrong for the `put` method.
- If I install the `NotarizedRoute` next to the `put` method, it -will- introspect the authentication, which will be wrong for the `get` method.
- If I install the route both places, I get an error saying the route has already been registered.

**Describe the solution you'd like**
Make it possible to register the same route multiple times, as long as the methods do not overlap.

**Comment by unredundant** [comment]
Hmmm... can't you just install the put documentation inside the authentication block?
