### ISSUE TITLE
Parameter examples missing descriptions

### ISSUE THREAD

**Issue by serpro69** [bkbnio/kompendium#379]
## **Describe the bug**

Seems like parameter examples are not rendered correctly.

```kotlin
Parameter(
    name = "page",
    `in` = Parameter.Location.query,
    schema = TypeDefinition.INT,
    description = "page number",
    required = false,
    examples = mapOf(
        "first page" to Parameter.Example(1),
        "last page" to Parameter.Example(-1),
        "3rd page" to Parameter.Example(3),
        "invalid input" to Parameter.Example(0)
    ),
)
```

Is rendered to:

![image](https://user-images.githubusercontent.com/22973227/201328646-1aa27707-00b6-433b-9584-620e276e9c45.png)

## **Expected behavior**

Examples should be rendered with the descriptions taken from map keys

Examples:
* `page=1` - first page 
* `page=-1` - last page
* `page=3` - 3rd page
* `page=0` - invalid input

**Comment by unredundant** [comment]
Oh nice good catch.  Would imagine we are just not applying the key on spec generation.  

I can probably find some time to tackle this next week, but if you're keen to get this fixed a PR would be welcome :)

**Comment by serpro69** [comment]
Will do if I find the time (not likely until after next week) :)

**Comment by unredundant** [comment]
I looked into this a bit, likely won't have time to address it in the near term, but it seems like I never updated the expected example object when going from OpenApi spec 3.0 to 3.1.

https://spec.openapis.org/oas/v3.1.0#example-object

So this might be a bigger lift than previously expected, potentially requiring a breaking change :(

**Comment by unredundant** [comment]
fixed in v4
