### ISSUE TITLE
Add AsyncAPI module for Ktor Web Sockets

### ISSUE THREAD

**Issue by unredundant** [bkbnio/kompendium#38]
Would be fantastic to explore integrating https://www.asyncapi.com with the `ktor-websockets` module to provide out of the box documentation for event-driven architectures.

**Comment by unredundant** [comment]
removing from V2 milestone as this can be added after the initial release as a complimentary module

**Comment by scolastico** [comment]
I would love to see that feature. 👍🏻

**Comment by unredundant** [comment]
I'm going to close this, I won't be getting to this in V4, and likely not any time in the foreseeable future.

Will welcome any PRs on this, but it is a pretty massive undertaking.
