### ISSUE TITLE
MapHandler should check for key type after serialization

### ISSUE THREAD

**Issue by bloonguyen1207** [bkbnio/kompendium#417]
**Describe the bug**

I have a response class that contains a type as a map key
```kotlin
@Serializable
data class SensorsThresholdResponse(
    val thresholds: Map<SensorType, SensorThreshold>
)
```

and `SensorType` has a serializer that encodes it into a string, which is a valid map key
```kotlin
object SensorTypeSerializer : KSerializer<SensorType> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("SensorType", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: SensorType) {
        encoder.encodeString(value.shortName)
    }
```

but I get an error with
```
JSON requires that map keys MUST be Strings. You provided SensorType
```

because MapHandler.handle check for key type before it serialized
```kotlin
require(type.arguments.first().type?.classifier as KClass<*> == String::class) {
      "JSON requires that map keys MUST be Strings.  You provided ${type.arguments.first().type}"
}
```

**Expected behavior**
MapHandler should check for key type after serialization

**Comment by unredundant** [comment]
From the openapi spec

>  Mapping keys MUST be string values, but tooling MAY convert response values to strings for comparison.

So, I guess we could allow more key types so long as they can be serialized to a string.  Would need someone else to implement this though, I won't have time in the near term to add that.  

And in the meantime, it should be pretty easy to just have the response type be `Map<String, SensorThreshold>` and serialize to a string yourself.

**Comment by unredundant** [comment]
I'm going to close this.  Will still welcome any PRs that can implement this in a clean manner, but, given that the current implementation solves the primary use case means that I won't be addressing this myself.
