### ISSUE TITLE
Provide access to `security` in PathOperation

### ISSUE THREAD

**Issue by bloonguyen1207** [bkbnio/kompendium#419]
**Is your feature request related to a problem? Please describe.**
When I have a route with both get and post, and each of them has a different access scope (read/write). There's currently no way to assign the scope to a specific operation. But I see there's a security field in `PathOperation`, how do I access this?

**Comment by unredundant** [comment]
Could you give some more detail? preferably a code example... 

If you are using Ktor auth plugin you should be able to achieve this by registering the appropriate authentication blocks as detailed here

https://bkbn.gitbook.io/kompendium/index-3/notarized_route#partial-authentication

**Comment by unredundant** [comment]
Also, could you expand on what you mean by scope? as in oauth grant scope? or some other scope

**Comment by bloonguyen1207** [comment]
I think security requirements is the right term here, sorry for the confusion. Here's an example.

I have this documentation for location, with get and post operations, and I want to provide read scope to my get operation, and write scope to my post operation, but I cannot access `PathOperation` security field directly since the builder doesn't provide it.

``` kotlin
install(NotarizedResource<LocationsResource>()) {
        tags = setOf(ApiTag.LOCATIONS.shortName)
        get = GetInfo.builder {
            security(mapOf("myAuth" to listOf("read")))     // can't do this
            summary("Location list")
            description("Get all locations")
            // other stuff
            ...
        }
        post = PostInfo.builder {
            summary("Add location")
            security(mapOf("myAuth" to listOf("write")))     // can't do this
            description("Add a new location")
            // other stuff
            ...
        }
    }
}
```

I can only provide security requirements for the whole resource like this

``` kotlin
install(NotarizedResource<LocationsResource>()) {
        tags = setOf(ApiTag.LOCATIONS.shortName)
        security(mapOf("myAuth" to listOf("read", "write")))
        get = GetInfo.builder {
            summary("Location list")
            description("Get all locations")
            // other stuff
            ...
        }
        post = PostInfo.builder {
            summary("Add location")
            description("Add a new location")
            // other stuff
            ...
        }
    }
}
```

I see that in `PathOperation` there is a security field, but I can't find a way to access it from the builder 😅 
Did I miss something maybe?

oas/src/main/kotlin/io/bkbn/kompendium/oas/path/PathOperation.kt

**Comment by unredundant** [comment]
ah yes i think we only currently expose that on the plugin configuration, not on the individual builder level.  I see what you are trying to do now :) 

Would definitely appreciate a pull request to add this feature! Can't make any promises about when I would be able to tackle this myself.

**Comment by unredundant** [comment]
will be fixed in v4
