### ISSUE TITLE
Add support for Response Headers

### ISSUE THREAD

**Issue by bronson-g** [bkbnio/kompendium#445]
**Is your feature request related to a problem? Please describe.**
My api uses response headers to inform caching strategies. There is currently no way for me to document that these headers are being used.

**Describe the solution you'd like**
I'd like to be able to specify the headers my routes will return.

**Describe alternatives you've considered**
I've considered allowing my api consumers to be unaware of the response headers.

**Additional context**
Response headers are part of the OAS.

**Comment by unredundant** [comment]
merged and cut new release, thanks again for the PR!
