### ISSUE TITLE
Build Kompendium-core 3.14.1 using Java 11

### ISSUE THREAD

**Issue by arthurv89** [bkbnio/kompendium#456]
**Is your feature request related to a problem? Please describe.**
When you want to use the Kompendium-core 3.14.1 dependency in a Java 11 project, it fails since the jar that's in Maven Central it's built using Java version 17.

**Describe the solution you'd like**
Build the jar using version 11, since that Java version is still supported as an LTS version. See: https://whichjdk.com/

**Describe alternatives you've considered**
I had to downgrade to version 2.3.5. That version seems to be built using version 11. However, that version is now deprecated, according to the docs:

> These docs are focused solely on Kompendium 3, previous versions should be considered deprecated and no longer maintained
(https://bkbn.gitbook.io/kompendium)

**Comment by unredundant** [comment]
> Widely used LTS version. Plan upgrade to version 17 within the next months.

We can downgrade to 11... but... seems like they're recommending for teams to upgrade to 17 in near future?

**Comment by unredundant** [comment]
https://endoflife.date/java looks like java 11 eol for active support is in 5 months, with security support for several more years.  since java 17 is backwards compatible with 11 I'll make a note to take care of this in the next couple of days

**Comment by arthurv89** [comment]
> Also out of curiosity.. did you also downgrade to Ktor 1? B/c Kompendium 2 only supports Ktor 1

Honestly, I'm still figuring out what is the best approach since upgrading Ktor to v2 was the initial goal.
For now, perhaps it's best if I build the dependency myself using Java 11, and upload it in our self-managed Artifactory.

My suggestion for the project is to release the jar using both Java 11 and Java 17. I've seen other projects that add a suffix. So for example:
Java 11: 3.14.1-jre11
Java 17: 3.14.1

**Comment by arthurv89** [comment]
One more question: are these dependencies now also deprecated? These highest version of these depencies is 2.3.5
- kompendium-annotations
- kompendium-auth
- kompendium-swagger-ui

**Comment by unredundant** [comment]
Ehhh I'd rather not break the versioning system like that, better to keep it simple IMO. 

If you are trying to upgrade to Ktor V2, then you will need Kompendium V3.  You can find the comparability matrix in the docs. 

And yep, several libs were removed in V3 as it was a pretty huge refactor.

**Comment by unredundant** [comment]
Oh now I remember why I bumped this to Java 17... Java 11 has pretty terrible Apple silicon support, and that makes configuring the gradle toolchain for Java 11 pretty annoying on apple silicon machines.

**Comment by unredundant** [comment]
Apologies, cuz this is gonna be kind of annoying for you, but I think if you absolutely need Java 11 support, your best bet is going to be to run a fork of Kompendium and just compile it yourself for Java 11.
