### ISSUE TITLE
Allow users to provide a custom serializer explicitly for Kompendium

### ISSUE THREAD

**Issue by chrimaeon** [bkbnio/kompendium#464]
**Describe the bug**
The generated OpenAPI JSON is not valid.

i.e. info object cannot have `nulls`. 
see https://github.com/OAI/OpenAPI-Specification/blob/9dff244e5708fbe16e768738f4f17cf3fddf4066/schemas/v3.1/schema.json#L82

**Comment by chrimaeon** [comment]
This results in tools like Postman or Swagger Editor to have i.e. HTTP verbs generated that are not defined.
<img width="219" alt="image" src="https://github.com/bkbnio/kompendium/assets/4489065/5c7a75b2-3728-404b-b48a-dcf1d155e88b">

**Comment by unredundant** [comment]
This is tricky, as it is not directly a bug in kompendium, and instead is a question of serialization.  

For example, this will not happen if an application uses Kotlinx serialization and sets `explicitNulls` to false.  

Since the default behavior is for Kompendium to leverage the serializer of the application, the question is, can we add an option for users to provide a custom serializer only for Kompendium.

**Comment by unredundant** [comment]
ah I see you made another ticket with this request.  I'm going to close this then, as there is nothing to do here, it all comes down to providing a custom serializer

**Comment by chrimaeon** [comment]
I don't get why you use the same Serializer anyway? For the "Components", the models, it might make sense but for the scaffold around, the base definition, you always should use your own internal serializer, otherwise you make the "user" responsible to generate valid OpenAPI definition.

**Comment by unredundant** [comment]
We use the same serializer because it allows us to inherit serialization for examples.  Otherwise, you will get examples that are encoded incorrectly.

**Comment by chrimaeon** [comment]
Yes, that makes sense for the Schemas and Components (and Examples) - code components that are actually create be the back-end and transmitted via the API - but not the scaffold you create like for `info`, `contact`, http methods and so on.

I guess you have your requirements, from a technical point of view it'd say its the wrong approach.

**Comment by unredundant** [comment]
you're welcome to push a PR with an improved approach, but all I hear from you is complaints with no alternatives :shrug:

**Comment by unredundant** [comment]
talk is cheap, show me code

**Comment by chrimaeon** [comment]
When I have time, I will - for now I found another library that fits my needs. :hat_tip:
