### ISSUE TITLE
Add the possibility to set a custom `Serializer`

### ISSUE THREAD

**Issue by chrimaeon** [bkbnio/kompendium#465]
**Is your feature request related to a problem? Please describe.**
For the generated OpenAPI definition it would be nice to have the option to set a custom serializer that i.e. is different to the one used for `ContentNegotiation`

Use-Case:

I cannot omit nulls in my API but want to avoid null properties in the API definition.

**Comment by chrimaeon** [comment]
for reference: #464

**Comment by unredundant** [comment]
will be fixed in v4
