### ISSUE TITLE
UnknownSchemaException in inherited variable

### ISSUE THREAD

**Issue by arthurv89** [bkbnio/kompendium#467]
**Describe the bug**
When using a super class with a property that's not overridden in the subclass, it can't generate the schema.

**To Reproduce**
Create the schema for 2 objects, where one is the subclass of the other.

```
class Comics(
    title: String,
    callToAction: String?,
    detailPageTitle: String?,
    val tags: List<Int>,
    val previews: List<PreviewV2>
) :
    Carousel(
        title,
        callToAction,
        detailPageTitle,
        Shape.RECTANGLE // Shape is defined here
    )
```

```
  sealed class Carousel(
      title: String,
      callToAction: String?,
      detailPageTitle: String?,
      val shape: Shape // Shape is defined here, in the superclass
  ) : WidgetV2(
      title,
      callToAction,
      detailPageTitle
  )
```

It throws an exception on SimpleObjectHandler:75

```
    val required = schemaConfigurator.serializableMemberProperties(clazz)
      .asSequence()
      .filterNot { it.javaField == null }
      .filterNot { prop -> prop.returnType.isMarkedNullable }
      .filterNot { prop ->
        clazz.primaryConstructor
          ?.parameters
          ?.find { it.name == prop.name }
          ?.isOptional
          ?: throw UnknownSchemaException( // Line 75
```
Here the debug values are as follows:

**prop.name**
"shape"

**clazz:** 
class WidgetV2$Carousel$Comics

**clazz.primaryConstructor?.parameters**
```
0 = {KParameterImpl@14845} parameter #0 title of fun `<init>`(String, String?, String?, List<Int>, List<PreviewV2>): WidgetV2.Carousel.Comics
1 = {KParameterImpl@14846} parameter #1 callToAction of fun `<init>`(String, String?, String?, List<Int>, List<PreviewV2>): WidgetV2.Carousel.Comics
2 = {KParameterImpl@14847} parameter #2 detailPageTitle of fun `<init>`(String, String?, String?, List<Int>, List<PreviewV2>): WidgetV2.Carousel.Comics
3 = {KParameterImpl@14848} parameter #3 tags of fun `<init>`(String, String?, String?, List<Int>, List<PreviewV2>): WidgetV2.Carousel.Comics
4 = {KParameterImpl@14849} parameter #4 previews of fun `<init>`(String, String?, String?, List<Int>, List<PreviewV2>): WidgetV2.Carousel.Comics
```

Note: the Shape type in an enum.

**Expected behavior**
I expected the library to ignore the "shape" schema since it's defined in the superclass, and not in the constructor of the subclass. In the subclass it has a default value assigned.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Version: 3.14.1

**Comment by arthurv89** [comment]
Additional information: it's because the props value in the method contains more types than the primary constructor.
See below:

**props**:
{
  "previews" : {
    "items" : {
      "$ref" : "#/components/schemas/PreviewV2"
    },
    "type" : "array"
  },
  "tags" : {
    "items" : {
      "type" : "number",
      "format" : "int32"
    },
    "type" : "array"
  },
  "callToAction" : {
    "oneOf" : [ {
      "type" : "null"
    }, {
      "type" : "string"
    } ]
  },
  "detailPageTitle" : {
    "oneOf" : [ {
      "type" : "null"
    }, {
      "type" : "string"
    } ]
  },
  "shape" : {
    "type" : "string",
    "format" : "shape"
  },
  "title" : {
    "type" : "string"
  }
}

**Comment by unredundant** [comment]
will be fixed in V4
