### ISSUE TITLE
Support Yaml format 

### ISSUE THREAD

**Issue by devbear0217** [bkbnio/kompendium#508]
Hi! First of all I want to thank you for this amazing library. Hope it will be mantained in the future

Is it possible to add Yaml serialization support to generate OpenAPI spec in yaml instead of JSON? If it's possible already then it would be cool to add an example or more details to documentation. 
If it's not then I think it would be cool to add support for YAML out of the box with additional module based on KotlinX serialization using something like https://github.com/charleskorn/kaml for this purpose. OpenAPI specs is often written in YAML format

**Comment by unredundant** [comment]
if it does work, let's add some documentation in that section about this use case :)

**Comment by unredundant** [comment]
oh btw the doc i linked assumes you are using `4.0.0-alpha`... which you are probably not 😅

**Comment by devbear0217** [comment]
> oh btw the doc i linked assumes you are using `4.0.0-alpha`... which you are probably not 😅

You're right :) I'm using latest available 3.3.1 version in Maven Central. But thanks, I'll try 4.0.0 with your suggentions then will report here

**Comment by unredundant** [comment]
so, I whipped up a quick playground example using yaml, and it seems fine from a generation perspective... there are a couple things that seem to be blockers with the `kaml` lib, specifically that I couldn't tell how to use a specific serializers module (needed to encode the use of `Any`), and it doesn't seem to support turning off explicit nulls, which all the openapi rendering tools really hate for some reason. 

so from a kompendium perspective, i think we are all good, but, in terms of whether or not kaml can support these needs, I'm less clear, though I didn't dig around much.
