### ISSUE TITLE
More automatic way to generate route definitions in OpenAPI

### ISSUE THREAD

**Issue by devbear0217** [bkbnio/kompendium#509]
Comparing with other non-Ktor frameworks and libraries Kompendium requires more handwork with route description through NotarizedRoute. There is no automatic generation like in springdoc-openapi and etc.

Is it possible to add annotation for function (like Composable in Jetpack Compose) and process it with KSP so route will be added automatically to OpenAPI spec without using Notarized Route?

Thanks for your job with Kompendium! You're awesome!

**Comment by unredundant** [comment]
Thanks :) means a lot

It is certainly possible, and I had an issue open for a long time regarding a KSP implementation.  

However, Doing spec generation via KSP would essentially become a ground up rewrite, so it won't be done in Kompendium, which will keep it's annotation-free approach.
