### ISSUE TITLE
Cannot access openapi.json

### ISSUE THREAD

**Issue by rolintoucour** [bkbnio/kompendium#565]
Hi,

I am pretty sure I am doing something wrong... The `/openapi.json` isn't accessible. Here is how I set it up:

```kotlin
CoroutineScope(coroutineContext).embeddedServer(
                Netty,
                port = port,
                parentCoroutineContext = coroutineContext,
            ) {
              routing {
                ... other plugins
                this@embeddedServer.install(NotarizedApplication()) {
                        spec =
                            OpenApiSpec(
                                info = Info(
                                    title = "title", version = "1.2.3", summary = "summary", description = "description",)
                            )
                    }
```

Strangely documentation says to do:

```kotlin
spec = {
        OpenApiSpec(
        // ...
      )
    }
```

which does not compil.

Any idea what's wrong?
Thanks

**Comment by unredundant** [comment]
sorry the docs are in a weird state as they are getting built out for 4.0, but currently that release has not happened yet.

for now you can reference the 3.x docs by referencing the code at the final release for 3.x 

https://github.com/bkbnio/kompendium/tree/v3.14.4/docs
