### ISSUE TITLE
Cannot find last release 4.0.0

### ISSUE THREAD

**Issue by laurentthiebaudezm** [bkbnio/kompendium#579]
**Describe the bug**

Hi 

On github I can see the last release is 4.0.0, however on maven central or repository I can only find 4.0.0-alpha (https://central.sonatype.com/artifact/io.bkbn/kompendium-core/versions) - is it expected?

(btw a comment on the doc: it is very clear and well written. However on https://bkbn.gitbook.io/kompendium/#notarizing-a-ktor-application I would expect to be able to open the `openapi.json` at the end. 

However this did not work, from the examples I understood that I needed ktor ContentNegotiation plugin also. You could argue that examples are there for this actually, however if there are prerequisites it could be worth explaining them).

**Comment by brizzbuzz** [comment]
This project is honestly in an unmaintained state.  I no longer work w/ Ktor or Kotlin, and on the whole, don't have the time to fix issues for the project.

I've debated making it a public archive project, but, have left it as is for now

**Comment by brizzbuzz** [comment]
The sonatype connection randomly breaking really took the remaining wind out of my sails, because sonatype is such a pain to debug, and it's left the project in a weird state b/c the documentation is all ready for 4.0, but 4.0 can't be released until the sonatype issue is figured out
