### ISSUE TITLE
Save to file system or application resources

### ISSUE THREAD

**Issue by oSumAtrIX** [bkbnio/kompendium#615]
The Ktor plugin "Swagger UI﻿" notes:

> This method tries to look up the OpenAPI specification in the application resources. Otherwise, it tries to read the OpenAPI specification from the file system using java.io.File.

Unless Kompendium saves the specification to the file system or application resources, there is no way to use the Swagger UI plugin for Ktor.

**Comment by brizzbuzz** [comment]
i'm not familiar with this plugin, is there a specific advantage over just using the kompendium helper route that serves swagger ui?

**Comment by anderssonw** [comment]
I didn't realise Kompendium offered its own helper route that serves the swagger ui at first, this might be the case here as well

Both OpenAPI and Swagger KTor plugins expect a file at startup (AFAIK), whereas kompendium does it runtime, so I don't really think they're compatible frameworks
