### ISSUE TITLE
OpenAPI spec version missing

### ISSUE THREAD

**Issue by oSumAtrIX** [bkbnio/kompendium#618]
The generated spec is missing the OpenAPI spec field. Swagger and Redoc don't render the spec as a result. Perhaps I am missing something?

I am not reproducing this issue on the playground and instead here: https://github.com/ReVanced/revanced-api/tree/kotlin

Here's what the output looks like:

<img width="701" alt="image" src="https://github.com/bkbnio/kompendium/assets/13122796/869ba233-e27d-4b26-92e4-34f87df8a3fa">

**Comment by brizzbuzz** [comment]
if I had to guess, their Kotlinx serializer is not [encoding defaults](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-encode-default/)

**Comment by brizzbuzz** [comment]
gonna close this but feel free to reopen if that doesn't solve this

**Comment by oSumAtrIX** [comment]
That did it!
