### ISSUE TITLE
Header parameter in Swagger not being added

### ISSUE THREAD

**Issue by oSumAtrIX** [bkbnio/kompendium#640]
Using 

`kompendium-core = "3.14.4"`` in https://github.com/ReVanced/revanced-api

I have this header:

```kt
private val authHeaderParameter = Parameter(
    name = "Authorization",
    `in` = Parameter.Location.header,
    schema = TypeDefinition.STRING,
    required = true,
    examples = mapOf("Bearer authentication" to Parameter.Example("Bearer abc123")),
)
```

I add it like this:

```kt
internal fun ApplicationCallPipeline.installNotarizedRoute(configure: NotarizedRoute.Config.() -> Unit = {}) =
    install(NotarizedRoute(), configure)

private fun Route.installAnnouncementRouteDocumentation() = installNotarizedRoute {
    tags = setOf("Announcements")

    parameters = listOf(authHeaderParameter)

    post = PostInfo.builder {
        description("Create a new announcement")
        summary("Create announcement")
        request {
            requestType<APIAnnouncement>()
            description("The new announcement")
        }
        response {
            description("The announcement is created")
            responseCode(HttpStatusCode.OK)
            responseType<Unit>()
        }
        canRespondUnauthorized()
    }
}
```

The parameter appears in Swagger:

![image](https://github.com/user-attachments/assets/edc97018-06dd-4917-85ed-5de2fb793c07)

But no auth header is present in the request:

![image](https://github.com/user-attachments/assets/f6a223e0-28f0-4210-9031-8b6cc815474c)

**Comment by brizzbuzz** [comment]
If it's not in the literal request, isn't this just a bug with the API, not with Kompendium itself? Kompendium is just an openapi documentation generator.

**Comment by oSumAtrIX** [comment]
It seems to be in the spec:

![image](https://github.com/user-attachments/assets/38a1c5e4-dd51-4227-9316-0cb07191661f)

But I am not sure if there needs to be something in addition in the spec for it to be added to the request. If this looks correct though, then the issue doesn't belong here. Reopen otherwise.
