### ISSUE TITLE
io.bkbn:kompendium-resources is not published for 4.0.1

### ISSUE THREAD

**Issue by nico1207** [bkbnio/kompendium#652]
**Describe the bug**

In https://github.com/bkbnio/kompendium/pull/648 publishing for the resources package was removed, so `io.bkbn:kompendium-resources` is not in the maven repository for 4.0.1.
Since we use Ktor Resources, we cannot upgrade to Kompendium 4 and support Ktor 3.

**To Reproduce**
1. Try to import io.bkbn:kompendium-resources:4.0.1 via Maven

**Expected behavior**
I expect the package to be available, or an explanation why it's not

**Comment by brizzbuzz** [comment]
oh yea weird, looks like that package specifically didn't get published.  thanks for reporting!

**Comment by brizzbuzz** [comment]
ok should be fixed in 4.0.2, just pushed that release
