### ISSUE TITLE
Support deprecating properties

### ISSUE THREAD

**Issue by oSumAtrIX** [bkbnio/kompendium#676]
OpenAPI 3.0 added support to deprecate properties of Schema objects: https://stackoverflow.com/a/49872992/11213244
Kompendium lacks this. Perhaps fields annotated annotated with `@Deprecated` can be marked as deprecated in the OpenAPI spec.

**Comment by brizzbuzz** [comment]
you can use enrichment 

https://bkbn.gitbook.io/kompendium/index-2/enrichment

**Comment by oSumAtrIX** [comment]
How would this work with generic types? Say I want to deprecate a field for my type but my response is a Set of that type. My Enrichment must be for Set<T> however, then I can not deprecate fields of T

**Comment by brizzbuzz** [comment]
hmm can you give it a shot and let me know if you get an error? that would be useful.  

if you can get it to error out, lets reopen this issue for that specifically.

**Comment by oSumAtrIX** [comment]
I am not sure how I would set a field for a type in a set using Kompendiums TypeEnrichment. Say you have a responseType Set<Animal> and you want to enrich Animal and set the field color to deprecated.

**Comment by oSumAtrIX** [comment]
@brizzbuzz Pinging in case you missed my reply
