### ISSUE TITLE
Support Java 8

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [bkbnio/kompendium#73]
Request was made to support Java 8.. hopefully this will be as simple as changing the supported compile version, I don't believe any features of Kompedium are explicitly incompatible with Java 8

**Comment by rgbrizzlehizzle** [comment]
@victor-lyan could you put out a PR for this? that way you could also ensure it works locally for your application as well :)

**Comment by victor-lyan** [comment]
> @victor-lyan could you put out a PR for this? that way you could also ensure it works locally for your application as well :)

sure, no problem :)

**Comment by rgbrizzlehizzle** [comment]
Release is going out for this now!
